### PR TITLE
pins correction according to the datasheet

### PR DESCRIPTION
**Pull request by abualkasim-bakeer**

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Could you please share screenshots of the schematic symbols and the footprints?

**Comment by abualkasim-bakeer** [comment]
> Could you please share screenshots of the schematic symbols and the footprints?

image

**Comment by abualkasim-bakeer** [comment]
> Could you please share screenshots of the schematic symbols and the footprints?

image

**Comment by abualkasim-bakeer** [comment]
Altium CAD
image
image

**Review by pavel-kirienko — APPROVED** [review]

**Pull request merged**
